services:
  - type: web
    name: smartweightsystems
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: ADMIN_PASSWORD
        value: Jones@2802
      - key: ADMIN_EMAIL
        value: jonesarock79703@gmail.com
      - key: SMTP_USER
        value: jonesarock79703@gmail.com
      - key: SMTP_PASS
        value: ifzm tqfb mxez whtq
